### Store location [POST]
::: warning
# Attempting to store another user's location will be rejected with a `403` response.
:::

+ Request (application/json)

    + Headers

            Authorization: bd3c37e77fca3a513947991ca4d3c40bf0098a4b

    + Body

            {
              "lat": 37.77493,
              "lon": -122.419416
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "lat": {
                  "type": "number"
                },
                "lon": {
                  "type": "number"
                }
              },
              "required": ["lat", "lon"]
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "Invalid authentication token."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 409 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 409,
              "error": "Invalid coordinates."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }
