### Delete [DELETE]
::: warning
# Attempting to delete another user's arrow will be rejected with a `403` response.
:::

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

+ Request

    + Headers

            Authorization: bd3c37e77fca3a513947991ca4d3c40bf0098a4b

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "Invalid authentication token."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 404,
              "error": "Arrow not found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }
