### Update [PUT]
::: warning
# Attempting to update another user's arrow will be rejected with a `403` response.
:::

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

+ Request (application/json)

    + Headers

            Authorization: bd3c37e77f...0bf0098a4b

    + Body

            {
              "date": 3552663511,
              "message": "I am looking for the one, the real one I saw on a bike this morning!",
              "medium": "bike",
              "location": {
                "lat": 37.77493,
                "lon": -122.419416
              }
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "date": {
                  "type": "integer",
                  "description": "Unix timestamp of the event."
                },
                "message": {
                  "type": "string"
                },
                "medium": {
                  "type": "string",
                  "enum": [
                    "bike",
                    "boat",
                    "bus",
                    "car",
                    "metro",
                    "plane",
                    "running",
                    "ship",
                    "sitting",
                    "train",
                    "walking"
                  ]
                },
                "location": {
                  "type": "object",
                  "properties": {
                    "lat": {
                      "type": "number"
                    },
                    "lon": {
                      "type": "number"
                    }
                  },
                  "required": ["lat", "lon"]
                }
              },
              "required": ["date", "message"]
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200,
              "arrow": {
                "id": "he9IwC6y"
              }
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "arrow": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": ["id"]
                }
              },
              "required": ["status", "arrow"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "Invalid authorization token."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 409 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 409,
              "error": "Invalid coordinates."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string",
                  "enum": [
                    "Invalid coordinates.",
                    "'date', 'message' and 'medium' are required properties."
                  ]
                }
              },
              "required": ["status", "error"]
            }
