FORMAT: 1A
HOST: http://localhost:8585
LOGO: https://raw.githubusercontent.com/Cupify/Documentation/master/assets/cupify.png

# Cupify API documentation

# Group User sessions
<!-- include(./sections/session.apib) -->

# Group User accounts
<!-- include(./sections/profile.apib) -->
