FORMAT: 1A
HOST: http://localhost:8585
LOGO: https://raw.githubusercontent.com/Cupify/Documentation/master/assets/cupify.png

# Cupify API documentation

# Group Sessions
<!-- include(./sections/session.apib) -->

# Group Accounts
<!-- include(./sections/profile.apib) -->

# Group Arrows
<!-- include(./sections/arrow.apib) -->
