## Arrow [/arrows/{arrowId}]

### Create [POST]
Add more information about this request.

+ Request (application/json)

    + Headers

            Authorization: sdfsfsdfsfdsfsfsdfdsfs

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200,
              "user": {
                "username": "cupify",
                "avatar": "https://cdn.cupify.me/avatar/h1u4Rye9.webp",
                "lastSeen": 1510795171
              }
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "user": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "integer"
                    },
                    "avatar": {
                      "type": "integer"
                    },
                    "lastSeen": {
                      "type": "integer",
                      "description": "Unix timestamp of user's last activity."
                    }
                  },
                  "required": ["username", "avatar", "lastSeen"]
                }
              },
              "required": ["status", "user"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The provided credentials are not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The requested user could not be found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

### Read [GET]
Add more information about this request.

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

+ Request (application/json)

    + Headers

            Authorization: sdfsfsdfsfdsfsfsdfdsfs

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200,
              "user": {
                "username": "cupify",
                "avatar": "https://cdn.cupify.me/avatar/h1u4Rye9.webp",
                "lastSeen": 1510795171
              }
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "user": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "integer"
                    },
                    "avatar": {
                      "type": "integer"
                    },
                    "lastSeen": {
                      "type": "integer",
                      "description": "Unix timestamp of user's last activity."
                    }
                  },
                  "required": ["username", "avatar", "lastSeen"]
                }
              },
              "required": ["status", "user"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The provided credentials are not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The requested user could not be found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }


### Update [PUT]
Arrows may only be updated by their owners.

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

+ Request

    + Headers

            Authorization: fsdfsfsfsdfsdfsdfd

    + Body

            {
              "email": "hello@cupify.me",
              "password": "54321",
              "gender": "male",
              "dob": 315964800,
              "status": "single",
              "about": "Hello, I am a musician."
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "gender": {
                  "type": "string",
                  "enum": [
                    "agender",
                    "intergender",
                    "female",
                    "male",
                    "none",
                    "non-binary",
                    "neutrois",
                    "transgender-man",
                    "transgender-woman",
                    "transsexual"
                  ]
                },
                "dob": {
                  "type": "integer"
                },
                "status": {
                  "type": "string"
                },
                "about": {
                  "type": "string"
                }
              }
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "The provided authentication token is not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 409 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 409,
              "error": "The provided email address is already in use."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

### Delete [DELETE]
Add more information about this request.

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

+ Request (application/json)

    + Headers

            Authorization: sdfsfsdfsfdsfsfsdfdsfs

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200,
              "user": {
                "username": "cupify",
                "avatar": "https://cdn.cupify.me/avatar/h1u4Rye9.webp",
                "lastSeen": 1510795171
              }
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "user": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "integer"
                    },
                    "avatar": {
                      "type": "integer"
                    },
                    "lastSeen": {
                      "type": "integer",
                      "description": "Unix timestamp of user's last activity."
                    }
                  },
                  "required": ["username", "avatar", "lastSeen"]
                }
              },
              "required": ["status", "user"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The provided credentials are not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The requested user could not be found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }


## Report [/arrows/{arrowId}/report]

+ Parameters

    + arrowId: hY7eRp9qB3 (string, required) - A unique arrow identifier.

### Report [POST]

+ Request (application/json)

    + Headers

            Authorization: sdfsfsdfsfdsfsfsdfdsfs

    + Body

            {
              "reason": "spam"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "reason": {
                  "type": "string",
                  "enum": ["spam", "offensive"]
                }
              },
              "required": ["reason"]
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "The provided authentication token is not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The requested arrow could not be found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }
