## Profile [/users/{userId}]
<!-- include(./profile/GET.apib) -->
<!-- include(./profile/PUT.apib) -->
<!-- include(./profile/DELETE.apib) -->

## Location [/users/location]
<!-- include(./profile/location/POST.apib) -->

## Report [/users/{userId}/report]
<!-- include(./profile/report/POST.apib) -->
