## Authentication [/auth]
### Login [POST]

+ Request Login with credentials (application/json)

    + Body

            {
              "username": "cupify",
              "password": "12345"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string",
                  "description": "Cupify account username."
                },
                "password": {
                  "type": "string",
                  "description": "Cupify account password."
                }
              },
              "required": ["username", "password"]
            }

+ Request Login with Facebook (application/json)

    + Body

            {
              "facebookToken": "fdsfsdfs"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "facebookToken": {
                  "type": "string",
                  "description": "Facebook session token."
                }
              },
              "required": ["facebookToken"]
            }

+ Request Login with Google (application/json)

    + Body

            {
              "googleToken": "fdsfsdfs"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "googleToken": {
                  "type": "string",
                  "description": "Google session token."
                }
              },
              "required": ["googleToken"]
            }

+ Request Login with Twitter (application/json)

    + Body

            {
              "twitterToken": "fdsfsdfs"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "twitterToken": {
                  "type": "string",
                  "description": "Twitter session token."
                }
              },
              "required": ["twitterToken"]
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200,
              "cupify": {
                "userId": "h1u4Rye9",
                "token": "dasdasdasdasda",
                "secret": "dasdaf"
              }
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "cupify": {
                  "type": "object",
                  "properties": {
                    "userId": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    },
                    "secret": {
                      "type": "string"
                    }
                  },
                  "required": ["token", "secret"]
                }
              },
              "required": ["status", "cupify"]
            }

+ Response 401 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 401,
              "error": "The provided credentials are not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }


### Logout [DELETE]
Add more information about this request.

+ Request Example

    + Headers

            Authorization: fsdfsfsfsdfsdfsdfd

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "The provided authentication token is not valid."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }
