### Report [POST]
::: warning
# Attempting to report a user more than once will be rejected with a `409` response.
:::

+ Parameters

    + userId: h1u4Rye9 (string, required) - A unique user identifier.

+ Request (application/json)

    + Headers

            Authorization: bd3c37e77f...0bf0098a4b

    + Body

            {
              "reason": "spam"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "reason": {
                  "type": "string",
                  "enum": ["spam", "offensive"]
                }
              },
              "required": ["reason"]
            }

+ Response 200 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 200
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                }
              },
              "required": ["status"]
            }

+ Response 403 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 403,
              "error": "Invalid authorization token."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 404 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 404,
              "error": "User not found."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }

+ Response 409 (application/json)

      + Headers

            Content-Transfer-Encoding: application/gzip

      + Body

            {
              "status": 409,
              "error": "User already reported."
            }

      + Schema

            {
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer"
                },
                "error": {
                  "type": "string"
                }
              },
              "required": ["status", "error"]
            }
